travis:
  secure:
    BINSTAR_TOKEN: QVn9rBJcU2qn63/2Updc8ytcjpcESW18weLOfM6t0zJt4RKcDgFq1M5mvbFlVh19xz/uSFoyWNViKZuTGvi9TU+Zv8U1W4BnTDMs8ikP86x/MhfvBEEA75sz6gugezviKPimh8DausQA2RM0l9DETa2ej84/2GnoLUVICNLMeo8+vgnElnF9QUXueDOm3H77blYxPwbqd14rLcXKV7HRYfyX4Cp02BDDL5IS+51VrBex/0qcLykk40MOHxTYTCBdGm4MUeuUtg3dx2fdkVCZy2hDuul1hdXH2rqCK3N0l/rxECUBvfz/ufxwwzDEjpHdm+kvvu1yGWuKPKMSVhaLcBkAeAnvhfhJde+mUl9mhCqL3OIKgaP+C3Ov51HdDF6WGr6QStHhH+Ve7Y/rsM26iMdMTQU686a1GuHsGMgU+xOfjupt8gzYR77bI2gDA+5AmnqSx0pWfkKTqGnAIDvQvMtt30dTMU0JI8VRhj/jKGoeqYWRNvf9kaY6L55DRpLQIkIYq4rZ/mRPTaDSq/MI5Jb2VgzI7ictccQubnyqSvZY89n3JSrioSrZ/2FkDn6TPcZhZdyXi0nDITjDJlmEXNDApZP+HBAgBkMKJGFaQwfQ0Q4dLhRC5V5FiCGLFq8pjoHluQL7j1bZLtlq3DIgRV9f2WvH4cNd11NlIHOfZhI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
